<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<?php use GeoEntreprise\Models\Domaine;
      use GeoEntreprise\Models\Entreprise;?>
<div class="page-header">
    <h1>
        Search domaines et entreprises
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["domaine_has_entreprise/new", "Affecter domaine à l'entreprise"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "domaine_has_entreprise/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldDomaineIdDomaine" class="col-sm-2 control-label">Domaine</label>
    <div class="col-sm-10">
      <?php
        $domaines=Domaine::find();

        echo $this->tag->select(['domaine_id_domaine',$domaines,'using'=>['id_domaine','nom']]);
       ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEntrepriseIdEntreprise" class="col-sm-2 control-label">Entreprise</label>
    <div class="col-sm-10">
      <?php
        $entreprises=Entreprise::find();

        echo $this->tag->select(['entreprise_id_entreprise',$entreprises,'using'=>['id_entreprise','nom']]);
       ?>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
