<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
use GeoEntreprise\Models\Entreprise ; 
?>

<div class="page-header">
    <h1>
        Search categorieemploye
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["categorieemploye/new", "Create categorieemploye"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "categorieemploye/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldType" class="col-sm-2 control-label">Type</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["type", "size" => 30, "class" => "form-control", "id" => "fieldType"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSalaire" class="col-sm-2 control-label">Salaire</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["salaire", "size" => 30, "class" => "form-control", "id" => "fieldSalaire"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNbr" class="col-sm-2 control-label">Nbr</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nbr", "type" => "number", "class" => "form-control", "id" => "fieldNbr"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNbrHeure" class="col-sm-2 control-label">Nbr Of Heure</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nbr_heure", "type" => "number", "class" => "form-control", "id" => "fieldNbrHeure"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEntrepriseId" class="col-sm-2 control-label">Entreprise</label>
    <div class="col-sm-10">
             <?php
        $entreprises=Entreprise::find();

        echo $this->tag->select(['entreprise_id',$entreprises,'using'=>['id_entreprise','nom']]);
       ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
