<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */

use GeoEntreprise\Models\Entreprise ; 
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["categorieemploye/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["categorieemploye/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id_categ</th>
            <th>Type</th>
            <th>Salaire</th>
            <th>Nbr</th>
            <th>Nbr Of Heure</th>
            <th>Entreprise</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $categorieemploye): ?>
            <tr>
                <td><?php echo $categorieemploye->id_categ ?></td>
            <td><?php echo $categorieemploye->type ?></td>
            <td><?php echo $categorieemploye->salaire ?></td>
            <td><?php echo $categorieemploye->nbr ?></td>
            <td><?php echo $categorieemploye->nbr_heure ?></td>
            <td><?php echo $categorieemploye->entreprise_id_entreprise ?></td>

                <td><?php echo $this->tag->linkTo(["categorieemploye/edit/" . $categorieemploye->id_categ, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["categorieemploye/delete/" . $categorieemploye->id_categ, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("categorieemploye/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("categorieemploye/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("categorieemploye/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("categorieemploye/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
