<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */

?>

<div class="page-header">
    <h1>
        Search entreprise
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["entreprise/new", "Create entreprise"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "entreprise/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldIdEntreprise" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_entreprise", "type" => "number", "class" => "form-control", "id_entreprise" => "fieldid_entreprise"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNom" class="col-sm-2 control-label">Nom</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nom", "size" => 30, "class" => "form-control", "id_entreprise" => "fieldNom"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSiren" class="col-sm-2 control-label">Siren</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["siren", "type" => "number", "class" => "form-control", "id_entreprise" => "fieldSiren"]) ?>
    </div>
</div>
<div class="form-group">
    <label for="fieldAdresse" class="col-sm-2 control-label">Adresse</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["adresse", "size" => 30, "class" => "form-control", "id_entreprise" => "fieldAdresse"]) ?>
    </div>
<div class="form-group">
    <label for="fieldDenomination" class="col-sm-2 control-label">Denomination</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["denomination", "size" => 30, "class" => "form-control", "id_entreprise" => "fieldDenomination"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldVille" class="col-sm-2 control-label">Ville</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["ville", "size" => 30, "class" => "form-control", "id_entreprise" => "fieldVille"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCodePostal" class="col-sm-2 control-label">Code Postale</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["code_postal", "size" => 30, "class" => "form-control", "id_entreprise" => "fieldCodePostal"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCapitalSocial" class="col-sm-2 control-label">Capitale Sociale</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["capital_social", "size" => 30, "class" => "form-control", "id_entreprise" => "fieldCapitalSocial"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFormeJuridique" class="col-sm-2 control-label">Forme Juridique</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["forme_juridique", "size" => 30, "class" => "form-control", "id_entreprise" => "fieldFormeJuridique"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCa" class="col-sm-2 control-label">CA</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["CA", "size" => 30, "class" => "form-control", "id_entreprise" => "fieldCa"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDateCreation" class="col-sm-2 control-label">Date De Creation</label>
    <div class="col-sm-10">

        <?php echo $this->tag->dateField(["date_creation", "type" => "date", "class" => "form-control", "id_entreprise" => "fieldDateCreation"]) ?>

    </div>
</div>

<div class="form-group">
    <label for="fieldRayonnement" class="col-sm-2 control-label">Rayonnement</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["rayonnement", "size" => 30, "class" => "form-control", "id_entreprise" => "fieldRayonnement"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
