
<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<?php
use GeoEntreprise\Models\Domaine;
?>
  <head>
 

     <style type="text/css">

h1 {
  font-family: Helvetica;
  font-weight: 100;
}
body {
  color:#333;
    text-align:center;
}
 </style>
    </head>


 

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["entreprise", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create entreprise
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "entreprise/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldNom" class="col-sm-2 control-label">Nom</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nom", "size" => 30, "class" => "form-control", "id_entreprise" => "fieldNom"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSiren" class="col-sm-2 control-label">Siren</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["siren", "type" => "number", "class" => "form-control", "id_entreprise" => "fieldSiren"]) ?>
    </div>
</div>
<div class="form-group">
    <label for="fieldAdresse" class="col-sm-2 control-label">Adresse</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["adresse", "size" => 30, "class" => "form-control", "id_entreprise" => "fieldAdresse"]) ?>
    </div>
<div class="form-group">
    <label for="fieldDenomination" class="col-sm-2 control-label">Denomination</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["denomination", "size" => 30, "class" => "form-control", "id_entreprise" => "fieldDenomination"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldVille" class="col-sm-2 control-label">Ville</label>
    <div class="col-sm-10">
      <select name="ville" >
      <?php

      $file = fopen("C:/wamp/www/GeoEntreprise/ville.txt", "r");
      if ($file) {
      while (($buffer = fgets($file, 4096)) !==false){ ?>
      <option value="<?php echo $buffer; ?>"><?php echo $buffer; ?></option>
      <?php }
      if (!feof($file)) {
      echo "Erreur: fgets() a échoué ";
      }
      fclose($file);
      }?>
      </select>

    </div>
</div>

<div class="form-group">
    <label for="fieldCodePostal" class="col-sm-2 control-label">Code Postale</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["code_postal", "size" => 30, "class" => "form-control", "id_entreprise" => "fieldCodePostal"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCapitalSocial" class="col-sm-2 control-label">Capital Sociale</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["capital_social", "size" => 30, "class" => "form-control", "id_entreprise" => "fieldCapitalSocial"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFormeJuridique" class="col-sm-2 control-label">Forme Juridique</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["forme_juridique", "size" => 30, "class" => "form-control", "id_entreprise" => "fieldFormeJuridique"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCa" class="col-sm-2 control-label">CA</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["CA", "size" => 30, "class" => "form-control", "id_entreprise" => "fieldCa"]) ?>
    </div>
</div>
<div class="form-group">
    <label for="fieldDomaineIdDomaine" class="col-sm-2 control-label">Domaine</label>
    <div class="col-sm-10">
           <?php
        $domaines=Domaine::find();  ?>       
          <select multiple name="domaines[]" > 
           
<?php foreach($domaines as $d){ ?>
                <option value="<?php echo $d->id_domaine;?>"><?php echo  $d->nom;     ?></option> 
<?php } ?>
    </select>
    </div>
</div>

<div class="form-group">

    <label for="fieldDateCreation" class="col-sm-2 control-label">Date De Creation</label>
    <div class="col-sm-10">
        <?php echo $this->tag->dateField(["date_creation", "type" => "date", "class" => "form-control", "id_entreprise" => "fieldDateCreation"]) ?>

    </div>
</div>

<div class="form-group">
    <label for="fieldRayonnement" class="col-sm-2 control-label">Rayonnement</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["rayonnement", "size" => 30, "class" => "form-control", "id_entreprise" => "fieldRayonnement"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>


<?php echo $this->tag->endForm(); ?>
