<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["entreprise/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["entreprise/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Nom</th>
            <th>Siren</th>
            <th>Adresse</th>
            <th>Denomination</th>
            <th>Ville</th>
            <th>Code Postale</th>
            <th>Capitale Sociale</th>
            <th>Forme Juridique</th>
            <th>CA</th>
            <th>Date De Creation</th>
            <th>Rayonnement</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $entreprise): ?>
            <tr>
                <td><?php echo $entreprise->id_entreprise ?></td>
            <td><?php echo $entreprise->nom ?></td>
            <td><?php echo $entreprise->siren ?></td>
            <td><?php echo $entreprise->adresse ?></td>
            <td><?php echo $entreprise->denomination ?></td>
            <td><?php echo $entreprise->ville ?></td>
            <td><?php echo $entreprise->code_postal ?></td>
            <td><?php echo $entreprise->capital_social ?></td>
            <td><?php echo $entreprise->forme_juridique ?></td>
            <td><?php echo $entreprise->CA ?></td>
            <td><?php echo $entreprise->date_creation ?></td>
            <td><?php echo $entreprise->rayonnement ?></td>

                <td><?php echo $this->tag->linkTo(["entreprise/edit/" . $entreprise->id_entreprise, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["entreprise/delete/" . $entreprise->id_entreprise, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("entreprise/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("entreprise/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("entreprise/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("entreprise/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
