<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<?php use GeoEntreprise\Models\Entreprise ;?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["transport/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["transport/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Matricule</th>
            <th>Modele</th>
            <th>Type</th>
            <th>Entreprise</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>


        <?php foreach ($page->items as $transport):
              $entreprise=Entreprise::findFirstByid_entreprise($transport->entreprise_id_entreprise );
          ?>
            <tr>
                <td><?php echo $transport->id_transport ?></td>
            <td><?php echo $transport->matricule ?></td>
            <td><?php echo $transport->modele ?></td>
            <td><?php echo $transport->type ?></td>
            <td><?php echo $entreprise->nom ?></td>

                <td><?php echo $this->tag->linkTo(["transport/edit/" . $transport->id_transport, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["transport/delete/" . $transport->id_transport, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("transport/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("transport/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("transport/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("transport/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
