<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<?php use GeoEntreprise\Models\Entreprise ;
 use GeoEntreprise\Models\Domaine ;?>
<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["etablissement", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create etablissement
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "etablissement/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>
<div class="form-group">
    <label for="fieldNom" class="col-sm-2 control-label">Nom</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nom", "type" => "number", "class" => "form-control", "id_etab" => "fieldnom"]) ?>
    </div>
</div>
<div class="form-group">
    <label for="fieldSiret" class="col-sm-2 control-label">Siret</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["siret", "type" => "number", "class" => "form-control", "id_etab" => "fieldSiret"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLongitude" class="col-sm-2 control-label">Longitude</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["longitude", "size" => 30, "class" => "form-control", "id_etab" => "fieldLongitude"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAltitude" class="col-sm-2 control-label">Altitude</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["altitude", "size" => 30, "class" => "form-control", "id_etab" => "fieldAltitude"]) ?>
    </div>
</div>
<div class="form-group">
    <label for="fieldDomaineIdDomaine" class="col-sm-2 control-label">Domaine</label>
    <div class="col-sm-10">
           <?php
        $domaines=Domaine::find();  ?>       
          <select multiple name="domaines[]" > 
           
<?php foreach($domaines as $d){ ?>
                <option value="<?php echo $d->id_domaine;?>"><?php echo  $d->nom;     ?></option> 
<?php } ?>
    </select>
    </div>
</div>
<div class="form-group">
    <label for="fieldEntrepriseIdEntreprise" class="col-sm-2 control-label">Entreprise</label>
    <div class="col-sm-10">
      <?php
        $entreprises=Entreprise::find();

        echo $this->tag->select(['entreprise_id_entreprise',$entreprises,'using'=>['id_entreprise','nom']]);
       ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
