<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<?php use GeoEntreprise\Models\Entreprise ;?>
<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["etablissement/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["etablissement/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
            <th>Etab</th>
            <th>Nom</th>
            <th>Siret</th>
            <th>Longitude</th>
            <th>Altitude</th>
            <th>Entreprise</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $etablissement):
              $entreprise=Entreprise::findFirstByid_entreprise($etablissement->entreprise_id_entreprise);
          ?>
            <tr>
            <td><?php echo $etablissement->id_etab ?></td>
            <td><?php echo $etablissement->nom?></td>
            <td><?php echo $etablissement->siret ?></td>
            <td><?php echo $etablissement->longitude ?></td>
            <td><?php echo $etablissement->altitude ?></td>
            <td><?php echo $entreprise->nom ?></td>

            <td><?php echo $this->tag->linkTo(["etablissement/edit/" . $etablissement->id_etab, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["etablissement/delete/" . $etablissement->id_etab, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("etablissement/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("etablissement/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("etablissement/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("etablissement/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
