
<html>
<head>
	<link href="..\..\..\..\GeoEntreprise\public\css\bootstrap.min.css" rel="stylesheet">
	<link href="..\..\..\..\GeoEntreprise\public\css\style.css"  rel="stylesheet">
	
</head>
<body> 
 <div class="col-md-8  col-md-offset-1 carousele" >
  <div id="myCarousel" class="carousel slide" data-ride="carousel" style=" width:700px; height: 300px !important;">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <img src="..\..\..\..\GeoEntreprise\public\img\e1.png"  alt="Los Angeles" style=" width:920px; height: 385px !important;">
     	<div class="carousel-caption">
	        <h3>Entreprises Collaborateurs Entrepreneurs </h3>
	        <p>en un seul click</p>
	     </div>
      </div>

      <div class="item">
        <img src="..\..\..\..\GeoEntreprise\public\img\e2.jpg" alt="Chicago" style=" width:920px; height: 385px !important;">
        <div class="carousel-caption">
	        <h3>Entreprise à proximité</h3>
	        <p>Choisir pour trouver ! </p>
	     </div>
      </div>
    
      <div class="item">
        <img src="..\..\..\..\GeoEntreprise\public\img\e3.jpg"  alt="New york" style=" width:920px; height: 385px !important;">
        <div class="carousel-caption">
	        <h3>Rendre votre E/se facile à trouver</h3>
	        <p>Contacter-nous</p>
	     </div>
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  </div>



 <div  id="myNavbar" class="navbar navbar-inverse navbar-fixed-top" role="navigation">
 <div class="container">
    <div class="navbar-header">
   <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
   </button>
  <a href="#" class="navbar-brand" id="n">GeoEntreprise</a> 
 </div>
  <div class="navbar-collapse collapse">
  	<ul class="nav navbar-nav navbar-right">
       <li><?php echo $this->tag->linkTo(["acceuil", "Qui sommes-nous ?"]) ?></li>
        <li><?php echo $this->tag->linkTo(["acceuil/localiser", "Localiser les entreprise"]) ?></li>
         <li><a href="#">Contact</a></li>
     </ul>
     </div>
  </div>
</div>

 
	   <div class="col-md-9 col-md-offset-1 ">
	  	<div class="panel  page">
			<div class="panel-body">
			<h3> IMPORTANCE DES CONNAISSANCES POUR UNE ENTREPRISE EN CROISSANCE </h3>
			Toutes les entreprises ont accès à un ensemble étendu de connaissances, qu'il s'agisse de leur compréhension des besoins des clients et de l'environnement professionnel ou des compétences et de l'expérience du personnel.<br>
La façon dont une entreprise rassemble, partage et exploite ces connaissances peut être essentielle afin de pouvoir se développer avec succès. Ceci ne s'applique pas uniquement aux énormes sociétés multinationales. La gestion des connaissances peut bénéficier à tout le monde, d'un kiosque à journaux local à une entreprise de fabrication.<br>
			</div>
	   </div>
	  	<div class="panel  page">
			<div class="panel-body">
			<h3 >L’ASSIOCATION « GeoEntreprise » A POUR MISSION PRINCIPAL DE : </h3>
				-<strong>Accompagner</strong> les entreprises, qui ouvrent déjà leurs portes au public ou qui en ont le projet, dans la<strong> professionnalisation</strong> et le <strong>développement </strong>de <strong>l’activité de visite d’entreprise régulière</strong>.<br>
                -<strong>Organiser</strong> des échanges entre les différents membres de l’association dans le but de <strong>constituer un réseau coopératif </strong>permettant le partage d’expérience et le progrès de chacun de ses membres.<br>
                -<strong>Présenter et valoriser les savoir-faire régionaux</strong> et également faire découvrir un certain nombre de métiers associés auprès du grand public et des jeunes qui représentent les salariés, entrepreneurs de demain.
			</div>
	   </div>
      </div>

 
  
</body>
</html>