
<?php 
use GeoEntreprise\Models\Domaine;
use GeoEntreprise\Models\Entreprise;
use GeoEntreprise\Models\Departement;
      ?>
<html>
 <head>


  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<script src="..\..\..\..\GeoEntreprise\public\js\jquery.min.js"></script>
<script src="..\..\..\..\GeoEntreprise\public\js\test.js"></script>
<link href="..\..\..\..\GeoEntreprise\public\css\bootstrap.min.css" rel="stylesheet">
  <link href="..\..\..\..\GeoEntreprise\public\css\style.css"  rel="stylesheet">

</head>
<body>
   <?php
    echo $this->tag->form(
        [
            "acceuil/submit",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

 <div  id="myNavbar" class="navbar navbar-inverse navbar-fixed-top" role="navigation">
 <div class="container">
    <div class="navbar-header">
   <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
   </button>
  
  <a href="#" class="navbar-brand" id="n">GeoEntreprise</a> 
 </div>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-right">
       <li><?php echo $this->tag->linkTo(["acceuil", "Qui sommes-nous ?"]) ?></li>
        <li><?php echo $this->tag->linkTo(["acceuil/localiser", "Localiser les entreprise"]) ?></li>
         <li><a href="#">Contact</a></li>
     </ul>
     </div>
  </div>
</div>







  
	
	<div class="div-center">
		
		<div id="map3"></div>

	
		
	</div>


    <div class="container conteneur">  
    <div class="col-md-6 contact ">
         <h3>Adresse</h3>
       <p> <p><div class="str"><img src="../../GeoEntreprise/public/img/localiser.jpg" width="15px" height="15px"> </div>
         
         <div  class="str"><strong>Emerging Business Factory</strong><br></div></p>
           62, Quartier Industriel Sidi Ghanem<br>
              طريق آسفي<br>
              Marrakech 40000<br>
                Maroc <br><br> </p>
              <h3>Contact</h3>  
              <p> <div class="str"><img src="../../GeoEntreprise/public/img/tel.PNG" width="18px" height="18px" class="str"> </div>
              <div class="str"> <h6>+212 6 70 14 87 42</h6></div></p> 
               
               <p><div class="str"> <img src="../../GeoEntreprise/public/img/email.PNG" width="18px" height="18px" class="str"> </div>

              <div class="str"> <h6>aboudia@webpick.info</h6></div></p> 

                </div>

    

   <div class="col-md-6 contact2">
      <div class="container col-md-10">
   <h3>Contactez nous</h3>

   <form class="form-horizontal" >
    <div class="form-group" ><br>
    <label for="usr">Name:</label>
  <input type="text" class="form-control " id="usr">
</div>
<div class="form-group">
  <label for="email">Email:</label>
  <input type="email" class="form-control" id="email">
    </div>
    <div class="form-group">
  <label for="sujet">Sujet:</label>
  <textarea class="form-control" rows="2" id="sujet"></textarea>
</div> 
<div class="form-group">
  <label for="message">Message:</label>
  <textarea class="form-control" rows="4" id="message"></textarea>
</div> 
<div class="form-group"> 
    
      <button type="submit" class="btn btn-info">Envoyer</button>

      

    
  </form>
  <?php echo $this->tag->endForm(); ?>
   
    <div align="right">
      <?= $this->tag->linkTo(['session/signup', '<i class="icon-ok icon-white"></i> Ajouter votre Entreprise', 'class' => 'btn btn-primary btn-info']) ?>
    </div>
  </div>
 </div>
</div>
	
	
	<script async defer
		src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDDkeI-kIm4S1_WR2xFykRqK6XE7HIL_ew&callback=initMap2">
		
	</script>



    
</body>
</html>