<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["domaine_has_etablissement", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit domaine_has_etablissement
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "domaine_has_etablissement/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldDomaineIdDomaine" class="col-sm-2 control-label">Domaine Of Id Of Domaine</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["domaine_id_domaine", "type" => "number", "class" => "form-control", "id" => "fieldDomaineIdDomaine"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEtablissementIdEtab" class="col-sm-2 control-label">Etablissement Of Id Of Etab</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["etablissement_id_etab", "type" => "number", "class" => "form-control", "id" => "fieldEtablissementIdEtab"]) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
