<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["contact", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit contact
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "contact/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldCin" class="col-sm-2 control-label">Cin</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["cin", "size" => 30, "class" => "form-control", "id_contact" => "fieldCin"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNom" class="col-sm-2 control-label">Nom</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nom", "size" => 30, "class" => "form-control", "id_contact" => "fieldNom"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPrenom" class="col-sm-2 control-label">Prenom</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["prenom", "size" => 30, "class" => "form-control", "id_contact" => "fieldPrenom"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEmail" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["email", "size" => 30, "class" => "form-control", "id_contact" => "fieldEmail"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDateAffectation" class="col-sm-2 control-label">Date d' Affectation</label>
    <div class="col-sm-10">
        <?php echo $this->tag->dateField(["date_affectation", "type" => "date", "class" => "form-control", "id_contact" => "fieldDateAffectation"]) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id_contact") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
